name: compile

on:
  pull_request:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.props'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x

      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/setup-ckan@1.1.1

      - uses: KSPModdingLibs/KSPBuildTools/.github/actions/compile@1.1.1
        with:
          solution-file-path: src/Kerbalism/Kerbalism.csproj
